{{- if not .Values.biblioteca.appSecret.existingSecret.enabled }}
{{- $secretName := (printf "%s-appsecret" (include "biblioteca.fullname" .)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/name: {{ include "biblioteca.name" . }}
    helm.sh/chart: {{ include "biblioteca.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: typesense
type: Opaque
data:
  {{- if .Values.biblioteca.appSecret.appSecret }}
  app-secret: {{ .Values.biblioteca.appSecret.appSecret | b64enc }}
  {{- else }}
  # Get the old secret (dry-run will return an empty map)
  {{- $currentSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}

  # check, if a secret is already set
  {{- if or (not $currentSecret) (not $currentSecret.data) }}
  # if not set, then generate a new password
  app-secret: {{ randAlphaNum 20 | b64enc }}
  {{ else }}
  # if set, then use the old value
  app-secret: {{ index $currentSecret.data "app-secret" }}
  {{ end }}
  {{- end }}
{{- end }}
