{{- if or .Values.mariadb.enabled .Values.externalDatabase.enabled }}
{{- if not .Values.externalDatabase.existingSecret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app.kubernetes.io/name: {{ include "biblioteca.name" . }}
    helm.sh/chart: {{ include "biblioteca.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.mariadb.enabled }}
  {{- $user := .Values.mariadb.auth.username }}
  db-username: {{ $user | b64enc | quote }}
  {{- $pass := .Values.mariadb.auth.password }}
  db-password: {{ $pass | b64enc | quote }}
  {{- $host := include "mariadb.primary.fullname" .Subcharts.mariadb }}
  {{- $db := .Values.mariadb.auth.database }}
  url: {{ (printf "mysql://%s:%s@%s/%s?charset=utf8" $user $pass $host $db) | b64enc | quote }}
  {{- else }}
  url: {{ .Values.externalDatabase.url | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
