{{- if .Values.typesense.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "biblioteca.fullname" . }}-typesense
  labels:
    app.kubernetes.io/name: {{ include "biblioteca.name" . }}
    helm.sh/chart: {{ include "biblioteca.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: typesense
    {{- with .Values.typesense.deploymentLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.typesense.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "biblioteca.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: typesense
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "biblioteca.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: typesense
        {{- with .Values.typesense.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.typesense.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.typesense.image.pullSecrets }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . }}
        {{- end}}
      {{- end }}
      containers:
        - args:
            - --data-dir
            - /data
            - "--api-key=$(API_KEY)"
            - --enable-cors
            {{- with .Values.typesense.extraArgs }}
            {{- range . }}
            - {{ . | quote }}
            {{- end}}
            {{- end }}
          image: typesense/typesense:27.1
          name: {{ .Chart.Name }}-typesense
          image: {{ printf "%s:%s" .Values.typesense.image.repository .Values.typesense.image.tag }}
          imagePullPolicy: {{ .Values.typesense.image.pullPolicy }}
          {{- with .Values.typesense.lifecycle }}
          lifecycle:
            {{- with .postStartCommand }}
            postStart:
              exec:
                command:
                  {{- toYaml . | nindent 18 }}
            {{- end }}
            {{- with .preStopCommand }}
            preStop:
              exec:
                command:
                  {{- toYaml . | nindent 18 }}
            {{- end }}
          {{- end }}
          
          env:
          - name: API_KEY
            valueFrom:
              secretKeyRef:
              {{- if .Values.typesense.apiKeySecret.existingSecret.enabled }}
                name: {{ .Values.typesense.apiKeySecret.existingSecret.secretName }}
                key: {{ .Values.typesense.apiKeySecret.existingSecret.apiKeyKey }}
              {{- else }}
                name: {{ printf "%s-typesense-apikey" (include "biblioteca.fullname" .) }}
                key: "api-key"
              {{- end }}
          {{- if .Values.biblioteca.extraEnv }}
          {{ toYaml . | nindent 10 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.typesense.containerPort }}
              protocol: TCP
          {{- with .Values.typesense.livenessProbe }}
          {{- if .enabled }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            successThreshold: {{ .successThreshold }}
            failureThreshold: {{ .failureThreshold }}
          {{- end }}
          {{- end }}
          {{- with .Values.typesense.readinessProbe }}
          {{- if .enabled }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            successThreshold: {{ .successThreshold }}
            failureThreshold: {{ .failureThreshold }}
          {{- end }}
          {{- end }}
          {{- with .Values.typesense.startupProbe }}
          {{- if .enabled }}
          startupProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            successThreshold: {{ .successThreshold }}
            failureThreshold: {{ .failureThreshold }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.typesense.resources | nindent 12 }}
          {{- with .Values.typesense.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /data
              name: data
            {{- if .Values.typesense.extraVolumeMounts }}
            {{ toYaml .Values.typesense.extraVolumeMounts | nindent 12 }}
            {{- end }}
      {{- with .Values.typesense.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.typesense.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.typesense.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      volumes:
        - name: data
          {{- if .Values.typesense.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.typesense.persistence.existingClaim }}{{ .Values.typesense.persistence.existingClaim }}{{- else }}{{ template "biblioteca.fullname" . }}-typesense{{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- with .Values.typesense.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.typesense.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{/* end-with podSecurityContext */}}
      {{- with .Values.typesense.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
