{{- if and .Values.externalTypesense.enabled (not .Values.externalTypesense.existingSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{- printf "%s-typesense-apikey" (include "biblioteca.chart" .) }}
  labels:
    app.kubernetes.io/name: {{ include "biblioteca.name" . }}
    helm.sh/chart: {{ include "biblioteca.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: typesense
type: Opaque
data:
  api-key: {{ .Values.externalTypesense.apiKey | b64enc }}
{{- end }}
