name: Lint and Test Charts

on:
  pull_request:
    types: [opened, reopened]

jobs:
  changes:
    runs-on: ubuntu-24.04

    outputs:
      src: ${{ steps.changes.outputs.src}}

    steps:
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        continue-on-error: true
        with:
          filters: |
            src:
              - 'charts/biblioteca/Chart.yaml'
              - 'charts/biblioteca/values.yaml'
              - 'charts/biblioteca/templates/**'

  lint:
    runs-on: ubuntu-24.04
    needs: changes
    if: needs.changes.outputs.src != 'false'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        id: lint
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

  test:
    runs-on: ubuntu-24.04
    needs: [changes, lint]
    # only run this job if there are helm chart file changes
    if: needs.changes.outputs.src != 'false'
    strategy:
      # continue with all the other jobs even if one fails
      fail-fast: false
      matrix:
        # each item in this list is a job with an isolated test VM
        test_cases:
          # test the helm chart with MariaDB subchart enabled
          - name: 'Default - no custom values'
            helm_args: '--namespace biblioteca --skip-clean-up --helm-extra-set-args "--set=fullnameOverride=biblioteca"'
            test: true

          # test the helm chart with external DB
          - name: External DB
            helm_args: '--helm-extra-set-args "--values charts/biblioteca/test-values/external_db.yaml"'


    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create kind cluster
        uses: helm/kind-action@v1.12.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Create biblioteca namespace
        if: steps.list-changed.outputs.changed == 'true'
        run: kubectl create namespace biblioteca

      - name: Run chart-testing (install ${{ matrix.test_cases.name }})
        id: install
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --target-branch ${{ github.event.repository.default_branch }} ${{ matrix.test_cases.helm_args }}

      - name: Run test for Biblioteca
        if: matrix.test_cases.test
        # applies a kubernetes job that uploads a file and then checks log of finished pod
        run: |
            EXIT=0
            kubectl config set-context --current --namespace=biblioteca && \
            kubectl wait --for=condition=Ready --timeout=300s pod -l app.kubernetes.io/name=mariadb && \
            kubectl wait --for=condition=Ready --timeout=300s pod -l app.kubernetes.io/name=biblioteca && \
            kubectl apply -f ./.github/tests/test_job.yaml --wait=true && \
            sleep 2 && \
            kubectl wait --for=condition=Complete --timeout=2m job/test-biblioteca || EXIT=1
            echo ""
            echo "------------------------------------------------------------"
            echo "Services"
            echo "------------------------------------------------------------"
            kubectl get service -o wide
            echo ""
            echo "------------------------------------------------------------"
            echo "Pod Description"
            echo "------------------------------------------------------------"
            kubectl describe pod -l app.kubernetes.io/name=biblioteca
            echo ""
            echo "------------------------------------------------------------"
            echo "Job description"
            echo "------------------------------------------------------------"
            kubectl describe job -l batch.kubernetes.io/job-name=test-biblioteca
            echo ""
            echo "------------------------------------------------------------"
            echo "Job logs"
            echo "------------------------------------------------------------"
            kubectl logs --ignore-errors --prefix --tail=-1 --all-containers -l batch.kubernetes.io/job-name=test-biblioteca
            echo ""
            echo "------------------------------------------------------------"
            echo "Biblioteca pod logs"
            echo "------------------------------------------------------------"
            kubectl logs --ignore-errors --prefix --tail=-1 --all-containers -l app.kubernetes.io/name=biblioteca
            exit $EXIT

  summary:
    runs-on: ubuntu-24.04
    needs: [changes, test]
    if: always()
    steps:
      - name: Summary
        run: if ${{ needs.changes.outputs.src != 'false' && needs.test.result != 'success' }}; then exit 1; fi