name: Renovate
on:
  schedule:
    # Run twice a day on weekdays
    - cron: '24 8,18 * * 1-5'
    # Run every 4 hours on weekends
    - cron: '24 */4 * * 0,6'
  push:
    branches:
      - main
    paths:
      - ".github/renovate-config.json"
      - ".github/workflows/renovate.yaml"
      - "scripts/**"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.14
        with:
          configurationFile: .github/renovate-config.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: 'debug'
