name: Renovate
on:
  schedule:
    # This should be every hour
    - cron: '0 * * * *'
  push:
    branches:
      - main
    paths:
      - ".github/renovate-config.json"
      - ".github/workflows/renovate.yml"
      - "renovate.json"
      - "scripts/**"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.3.6
        with:
          configurationFile: .github/renovate-config.json
          token: ${{ secrets.RENOVATE_TOKEN }}
